---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 -}}
      {{ end }}
      containers:
        - env:
            - name: PLEX_SECTION
              value: {{ .Values.settings.plex_section }}
            - name: PLEX_URL
              value: {{ .Values.settings.plex_url | required ".Values.config.plex_url is required" }}
            - name: ANI_USERNAME
              value: {{ .Values.settings.ani_username | required ".Values.config.ani_username is required" }}
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  key: plex-token
                  name: {{ include "common.names.fullname" . }}
            - name: ANI_TOKEN
              valueFrom:
                secretKeyRef:
                  key: ani-token
                  name: {{ include "common.names.fullname" . }}
            {{- if .Values.settings.interval }}
            - name: INTERVAL
              value: {{ .Values.settings.interval | quote }}
            {{- end }}
            {{- if .Values.settings.plex_episode_count_priority }}
            - name: PLEX_EPISODE_COUNT_PRIORITY
              value: {{ .Values.settings.plex_episode_count_priority | quote }}
            {{- end }}
            {{- if .Values.settings.sync_ratings }}
            - name: SYNC_RATINGS
              value: {{ .Values.settings.sync_ratings | quote }}
            {{- end }}
            {{- if .Values.settings.skip_list_update }}
            - name: SKIP_LIST_UPDATE
              value: {{ .Values.settings.skip_list_update | quote }}
            {{- end }}
            {{- with .Values.envVars }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          image: {{ .Values.image }}
          name: {{ include "common.names.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.custom_mappings .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.custom_mappings }}
            - mountPath: /plexanisync/custom_mappings.yaml
              name: {{ include "common.names.fullname" . }}
              subPath: custom_mappings.yaml
            {{- end }}
            {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if or .Values.custom_mappings .Values.volumes }}
      volumes:
        {{- if .Values.custom_mappings }}
        - configMap:
            defaultMode: 0777
            name: {{ include "common.names.fullname" . }}
          name: {{ include "common.names.fullname" . }}
        {{- end }}
        {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- end }}