[tool.poetry]
name = "plexanisync"
version = "1.3.24"
description = "Sync anime library to Anilist"
authors = ["RickDB <RickDB@gmail.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.2"
coloredlogs = "^15.0.1"
requests = "^2.28.2"
inflect = "^6.0.4"
jsonschema = "^4.17"
plexapi = "^4.13.4"
ruyaml = "^0.91.0"
sgqlc = "^16.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
pylint = "^2.17.2"
pylint-exit = "^1.2.0"
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
