nameOverride:
fullnameOverride:
namespaceOverride:

custom_mappings:

envVars: []

cronjob:
  enabled: true
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  schedule: '* */1 * * *'
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1

image: ghcr.io/rickdb/plexanisync:latest

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

settings:
  plex_section: Anime|Anime Movies
  plex_url:
  ani_username:
  plex_episode_count_priority:
  sync_ratings:
  skip_list_update:
  # interval is forced to 0 when cronjob.enabled
  interval:

securityContext:

tokens:
  ani:
  plex:

volumes: []
volumeMounts: []