{{- if not .Values.cronjob.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 -}}
      {{ end }}
      containers:
        - env: {{- include "container.env" . | nindent 10 }}
          - name: INTERVAL
            value: {{ .Values.settings.interval | quote }}
          image: {{ .Values.image }}
          name: {{ include "common.names.name" . }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- include "container.volumeMounts" . | indent 10 -}}
      {{- include "pod.volumes" . | nindent 6 -}}
{{- end }}