name: Build and Push Docker Image to docker.com and ghcr.io

on: 
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      imagename:
        required: true
        type: string
      platforms:
        required: true
        type: string
      eventname:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_IO: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }} 
    steps:
        # Set IMAGE_NAMES to ghcr.io, also set to docker.io if building a tag or master
      - name: Set image names
        run: |          
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "IMAGE_NAMES<<$EOF" >> $GITHUB_ENV
          echo "ghcr.io/${{ inputs.imagename }}" >> $GITHUB_ENV
          if [[ ${{ env.DOCKER_IO }} == true ]]; then
            echo "${{ inputs.imagename }}" >> $GITHUB_ENV
          fi
          echo "$EOF" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Add tags to metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.IMAGE_NAMES }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Log into docker.com registry
        if: env.DOCKER_IO == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ inputs.eventname != 'pull_request' }}
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
