name: Build and Push Docker Image to docker.com and ghcr.io

on: 
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      imagename:
        required: true
        type: string
      platforms:
        required: true
        type: string
      eventname:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        # Set IMAGE_NAMES to ghcr.io, additionally add docker.io if building a tag or master
        # Limit platforms to amd64 if building for pull requests
      - name: Set variables
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "IMAGE_NAMES<<$EOF" >> $GITHUB_ENV
          if [[ ${{ github.ref }} == *"refs/tags/"* ]] || [[ ${{ github.ref }} == "refs/heads/master" ]]; then
            DOCKER_IO=true
            echo "${{ inputs.imagename }}" >> $GITHUB_ENV
          fi
          echo "ghcr.io/${{ inputs.imagename }}" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          if [[ -n "$DOCKER_IO" ]]; then
            echo "DOCKER_IO=true" >> $GITHUB_ENV
          fi

          if [[ ${{ inputs.eventname }} == 'pull_request' ]]; then
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
          else
            echo "PLATFORMS=${{ inputs.platforms }}" >> $GITHUB_ENV
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Add tags to metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.IMAGE_NAMES }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Log into docker.com registry
        if: ${{ env.DOCKER_IO }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ inputs.eventname != 'pull_request' }}
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
